/*
Copyright 2018 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/knative/eventing-sources/contrib/rabbitmq/pkg/apis/sources/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRabbitMQSources implements RabbitMQSourceInterface
type FakeRabbitMQSources struct {
	Fake *FakeSourcesV1alpha1
	ns   string
}

var rabbitmqsourcesResource = schema.GroupVersionResource{Group: "sources.eventing.knative.dev", Version: "v1alpha1", Resource: "rabbitmqsources"}

var rabbitmqsourcesKind = schema.GroupVersionKind{Group: "sources.eventing.knative.dev", Version: "v1alpha1", Kind: "RabbitMQSource"}

// Get takes name of the rabbitMQSource, and returns the corresponding rabbitMQSource object, and an error if there is any.
func (c *FakeRabbitMQSources) Get(name string, options v1.GetOptions) (result *v1alpha1.RabbitMQSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(rabbitmqsourcesResource, c.ns, name), &v1alpha1.RabbitMQSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RabbitMQSource), err
}

// List takes label and field selectors, and returns the list of RabbitMQSources that match those selectors.
func (c *FakeRabbitMQSources) List(opts v1.ListOptions) (result *v1alpha1.RabbitMQSourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(rabbitmqsourcesResource, rabbitmqsourcesKind, c.ns, opts), &v1alpha1.RabbitMQSourceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RabbitMQSourceList{ListMeta: obj.(*v1alpha1.RabbitMQSourceList).ListMeta}
	for _, item := range obj.(*v1alpha1.RabbitMQSourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested rabbitMQSources.
func (c *FakeRabbitMQSources) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(rabbitmqsourcesResource, c.ns, opts))

}

// Create takes the representation of a rabbitMQSource and creates it.  Returns the server's representation of the rabbitMQSource, and an error, if there is any.
func (c *FakeRabbitMQSources) Create(rabbitMQSource *v1alpha1.RabbitMQSource) (result *v1alpha1.RabbitMQSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(rabbitmqsourcesResource, c.ns, rabbitMQSource), &v1alpha1.RabbitMQSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RabbitMQSource), err
}

// Update takes the representation of a rabbitMQSource and updates it. Returns the server's representation of the rabbitMQSource, and an error, if there is any.
func (c *FakeRabbitMQSources) Update(rabbitMQSource *v1alpha1.RabbitMQSource) (result *v1alpha1.RabbitMQSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(rabbitmqsourcesResource, c.ns, rabbitMQSource), &v1alpha1.RabbitMQSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RabbitMQSource), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRabbitMQSources) UpdateStatus(rabbitMQSource *v1alpha1.RabbitMQSource) (*v1alpha1.RabbitMQSource, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(rabbitmqsourcesResource, "status", c.ns, rabbitMQSource), &v1alpha1.RabbitMQSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RabbitMQSource), err
}

// Delete takes name of the rabbitMQSource and deletes it. Returns an error if one occurs.
func (c *FakeRabbitMQSources) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(rabbitmqsourcesResource, c.ns, name), &v1alpha1.RabbitMQSource{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRabbitMQSources) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(rabbitmqsourcesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.RabbitMQSourceList{})
	return err
}

// Patch applies the patch and returns the patched rabbitMQSource.
func (c *FakeRabbitMQSources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.RabbitMQSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(rabbitmqsourcesResource, c.ns, name, data, subresources...), &v1alpha1.RabbitMQSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RabbitMQSource), err
}
