/*
Copyright 2018 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/knative/eventing-sources/contrib/rabbitmq/pkg/apis/sources/v1alpha1"
	scheme "github.com/knative/eventing-sources/contrib/rabbitmq/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// RabbitMQSourcesGetter has a method to return a RabbitMQSourceInterface.
// A group's client should implement this interface.
type RabbitMQSourcesGetter interface {
	RabbitMQSources(namespace string) RabbitMQSourceInterface
}

// RabbitMQSourceInterface has methods to work with RabbitMQSource resources.
type RabbitMQSourceInterface interface {
	Create(*v1alpha1.RabbitMQSource) (*v1alpha1.RabbitMQSource, error)
	Update(*v1alpha1.RabbitMQSource) (*v1alpha1.RabbitMQSource, error)
	UpdateStatus(*v1alpha1.RabbitMQSource) (*v1alpha1.RabbitMQSource, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.RabbitMQSource, error)
	List(opts v1.ListOptions) (*v1alpha1.RabbitMQSourceList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.RabbitMQSource, err error)
	RabbitMQSourceExpansion
}

// rabbitMQSources implements RabbitMQSourceInterface
type rabbitMQSources struct {
	client rest.Interface
	ns     string
}

// newRabbitMQSources returns a RabbitMQSources
func newRabbitMQSources(c *SourcesV1alpha1Client, namespace string) *rabbitMQSources {
	return &rabbitMQSources{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the rabbitMQSource, and returns the corresponding rabbitMQSource object, and an error if there is any.
func (c *rabbitMQSources) Get(name string, options v1.GetOptions) (result *v1alpha1.RabbitMQSource, err error) {
	result = &v1alpha1.RabbitMQSource{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("rabbitmqsources").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of RabbitMQSources that match those selectors.
func (c *rabbitMQSources) List(opts v1.ListOptions) (result *v1alpha1.RabbitMQSourceList, err error) {
	result = &v1alpha1.RabbitMQSourceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("rabbitmqsources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested rabbitMQSources.
func (c *rabbitMQSources) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("rabbitmqsources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a rabbitMQSource and creates it.  Returns the server's representation of the rabbitMQSource, and an error, if there is any.
func (c *rabbitMQSources) Create(rabbitMQSource *v1alpha1.RabbitMQSource) (result *v1alpha1.RabbitMQSource, err error) {
	result = &v1alpha1.RabbitMQSource{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("rabbitmqsources").
		Body(rabbitMQSource).
		Do().
		Into(result)
	return
}

// Update takes the representation of a rabbitMQSource and updates it. Returns the server's representation of the rabbitMQSource, and an error, if there is any.
func (c *rabbitMQSources) Update(rabbitMQSource *v1alpha1.RabbitMQSource) (result *v1alpha1.RabbitMQSource, err error) {
	result = &v1alpha1.RabbitMQSource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("rabbitmqsources").
		Name(rabbitMQSource.Name).
		Body(rabbitMQSource).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *rabbitMQSources) UpdateStatus(rabbitMQSource *v1alpha1.RabbitMQSource) (result *v1alpha1.RabbitMQSource, err error) {
	result = &v1alpha1.RabbitMQSource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("rabbitmqsources").
		Name(rabbitMQSource.Name).
		SubResource("status").
		Body(rabbitMQSource).
		Do().
		Into(result)
	return
}

// Delete takes name of the rabbitMQSource and deletes it. Returns an error if one occurs.
func (c *rabbitMQSources) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("rabbitmqsources").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *rabbitMQSources) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("rabbitmqsources").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched rabbitMQSource.
func (c *rabbitMQSources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.RabbitMQSource, err error) {
	result = &v1alpha1.RabbitMQSource{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("rabbitmqsources").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
